### ISSUE TITLE
Challenge edit form

### ISSUE THREAD

**Issue by dulldesk** [KuriusMTL/HackItForward#24] opened 2020-09-11 04:32 UTC
We need a form to allow for editing challenge "submissions". Editing a challenge should be limited to creators.

**Comment by fluix-dev** [comment] 2020-09-11 04:32
Duplicate of #17

**Comment by fluix-dev** [comment] 2020-09-11 04:33
In case it isn't clear what I mean, the creation and editing forms are generally the same thing.

**Closed as completed by fluix-dev** 2020-09-11 04:32 UTC
Labels: duplicate
